insert into public.canton (id, provincia_id, nombre) OVERRIDING SYSTEM VALUE values(5,4,'TULCAN');
insert into public.canton (id, provincia_id, nombre) OVERRIDING SYSTEM VALUE values(10,4,'MONTUFAR');
insert into public.canton (id, provincia_id, nombre) OVERRIDING SYSTEM VALUE values(11,26,'ALEMANIA');
insert into public.canton (id, provincia_id, nombre) OVERRIDING SYSTEM VALUE values(15,4,'ESPEJO');
insert into public.canton (id, provincia_id, nombre) OVERRIDING SYSTEM VALUE values(20,4,'MIRA');
insert into public.canton (id, provincia_id, nombre) OVERRIDING SYSTEM VALUE values(21,28,'ARGENTINA');
insert into public.canton (id, provincia_id, nombre) OVERRIDING SYSTEM VALUE values(25,4,'BOLIVAR');
insert into public.canton (id, provincia_id, nombre) OVERRIDING SYSTEM VALUE values(30,10,'IBARRA');
insert into public.canton (id, provincia_id, nombre) OVERRIDING SYSTEM VALUE values(31,26,'AUSTRALIA');
insert into public.canton (id, provincia_id, nombre) OVERRIDING SYSTEM VALUE values(35,10,'OTAVALO');
insert into public.canton (id, provincia_id, nombre) OVERRIDING SYSTEM VALUE values(40,10,'COTACACHI');
insert into public.canton (id, provincia_id, nombre) OVERRIDING SYSTEM VALUE values(41,26,'AUSTRIA');
insert into public.canton (id, provincia_id, nombre) OVERRIDING SYSTEM VALUE values(45,10,'ANTONIO ANTE');
insert into public.canton (id, provincia_id, nombre) OVERRIDING SYSTEM VALUE values(50,10,'PIMAMPIRO');
insert into public.canton (id, provincia_id, nombre) OVERRIDING SYSTEM VALUE values(51,26,'BELGICA');
insert into public.canton (id, provincia_id, nombre) OVERRIDING SYSTEM VALUE values(55,10,'URCUQUI');
insert into public.canton (id, provincia_id, nombre) OVERRIDING SYSTEM VALUE values(60,17,'QUITO');
insert into public.canton (id, provincia_id, nombre) OVERRIDING SYSTEM VALUE values(61,28,'BOLIVIA');
insert into public.canton (id, provincia_id, nombre) OVERRIDING SYSTEM VALUE values(65,17,'CAYAMBE');
insert into public.canton (id, provincia_id, nombre) OVERRIDING SYSTEM VALUE values(70,17,'MEJIA');
insert into public.canton (id, provincia_id, nombre) OVERRIDING SYSTEM VALUE values(71,28,'BRASIL');
insert into public.canton (id, provincia_id, nombre) OVERRIDING SYSTEM VALUE values(75,17,'PEDRO MONCAYO');
insert into public.canton (id, provincia_id, nombre) OVERRIDING SYSTEM VALUE values(80,17,'RUMIÑAHUI');
insert into public.canton (id, provincia_id, nombre) OVERRIDING SYSTEM VALUE values(81,27,'CANADA');
insert into public.canton (id, provincia_id, nombre) OVERRIDING SYSTEM VALUE values(85,23,'SANTO DOMINGO');
insert into public.canton (id, provincia_id, nombre) OVERRIDING SYSTEM VALUE values(90,18,'TISALEO');
insert into public.canton (id, provincia_id, nombre) OVERRIDING SYSTEM VALUE values(91,28,'COLOMBIA');
insert into public.canton (id, provincia_id, nombre) OVERRIDING SYSTEM VALUE values(95,9,'BALAO');
insert into public.canton (id, provincia_id, nombre) OVERRIDING SYSTEM VALUE values(100,5,'LATACUNGA');
insert into public.canton (id, provincia_id, nombre) OVERRIDING SYSTEM VALUE values(101,26,'COREA (SUR) REPUBLICA DE');
insert into public.canton (id, provincia_id, nombre) OVERRIDING SYSTEM VALUE values(105,5,'PUJILI');
insert into public.canton (id, provincia_id, nombre) OVERRIDING SYSTEM VALUE values(110,5,'SALCEDO');
insert into public.canton (id, provincia_id, nombre) OVERRIDING SYSTEM VALUE values(111,28,'COSTA RICA');
insert into public.canton (id, provincia_id, nombre) OVERRIDING SYSTEM VALUE values(115,5,'SAQUISILI');
insert into public.canton (id, provincia_id, nombre) OVERRIDING SYSTEM VALUE values(120,5,'PANGUA');
insert into public.canton (id, provincia_id, nombre) OVERRIDING SYSTEM VALUE values(121,28,'CUBA');
insert into public.canton (id, provincia_id, nombre) OVERRIDING SYSTEM VALUE values(125,9,'COLIMES');
insert into public.canton (id, provincia_id, nombre) OVERRIDING SYSTEM VALUE values(130,19,'NANGARITZA');
insert into public.canton (id, provincia_id, nombre) OVERRIDING SYSTEM VALUE values(131,28,'CHILE');
insert into public.canton (id, provincia_id, nombre) OVERRIDING SYSTEM VALUE values(135,18,'AMBATO');
insert into public.canton (id, provincia_id, nombre) OVERRIDING SYSTEM VALUE values(140,18,'PELILEO');
insert into public.canton (id, provincia_id, nombre) OVERRIDING SYSTEM VALUE values(141,26,'CHINA');
insert into public.canton (id, provincia_id, nombre) OVERRIDING SYSTEM VALUE values(145,18,'PILLARO');
insert into public.canton (id, provincia_id, nombre) OVERRIDING SYSTEM VALUE values(150,18,'BAÑOS');
insert into public.canton (id, provincia_id, nombre) OVERRIDING SYSTEM VALUE values(155,18,'PATATE');
insert into public.canton (id, provincia_id, nombre) OVERRIDING SYSTEM VALUE values(160,18,'QUERO');
insert into public.canton (id, provincia_id, nombre) OVERRIDING SYSTEM VALUE values(161,28,'EL SALVADOR');
insert into public.canton (id, provincia_id, nombre) OVERRIDING SYSTEM VALUE values(165,2,'GUARANDA');
insert into public.canton (id, provincia_id, nombre) OVERRIDING SYSTEM VALUE values(170,2,'CHIMBO');
insert into public.canton (id, provincia_id, nombre) OVERRIDING SYSTEM VALUE values(171,26,'ESPAÑA');
insert into public.canton (id, provincia_id, nombre) OVERRIDING SYSTEM VALUE values(175,2,'SAN MIGUEL');
insert into public.canton (id, provincia_id, nombre) OVERRIDING SYSTEM VALUE values(180,2,'CHILLANES');
insert into public.canton (id, provincia_id, nombre) OVERRIDING SYSTEM VALUE values(181,27,'ESTADOS UNIDOS DE AMERICA');
insert into public.canton (id, provincia_id, nombre) OVERRIDING SYSTEM VALUE values(185,2,'ECHEANDIA');
insert into public.canton (id, provincia_id, nombre) OVERRIDING SYSTEM VALUE values(190,6,'CHAMBO');
insert into public.canton (id, provincia_id, nombre) OVERRIDING SYSTEM VALUE values(191,26,'FRANCIA');
insert into public.canton (id, provincia_id, nombre) OVERRIDING SYSTEM VALUE values(195,6,'RIOBAMBA');
insert into public.canton (id, provincia_id, nombre) OVERRIDING SYSTEM VALUE values(200,6,'GUANO');
insert into public.canton (id, provincia_id, nombre) OVERRIDING SYSTEM VALUE values(201,26,'REINO UNIDO DE GRAN BRETAÑA E IRLANDA DEL NORTE');
insert into public.canton (id, provincia_id, nombre) OVERRIDING SYSTEM VALUE values(205,6,'COLTA');
insert into public.canton (id, provincia_id, nombre) OVERRIDING SYSTEM VALUE values(210,6,'GUAMOTE');
insert into public.canton (id, provincia_id, nombre) OVERRIDING SYSTEM VALUE values(211,28,'GUATEMALA');
insert into public.canton (id, provincia_id, nombre) OVERRIDING SYSTEM VALUE values(215,6,'ALAUSI');
insert into public.canton (id, provincia_id, nombre) OVERRIDING SYSTEM VALUE values(220,6,'CHUNCHI');
insert into public.canton (id, provincia_id, nombre) OVERRIDING SYSTEM VALUE values(221,28,'HONDURAS');
insert into public.canton (id, provincia_id, nombre) OVERRIDING SYSTEM VALUE values(225,6,'PENIPE');
insert into public.canton (id, provincia_id, nombre) OVERRIDING SYSTEM VALUE values(230,13,'FLAVIO ALFARO');
insert into public.canton (id, provincia_id, nombre) OVERRIDING SYSTEM VALUE values(231,26,'HUNGRIA');
insert into public.canton (id, provincia_id, nombre) OVERRIDING SYSTEM VALUE values(235,3,'AZOGUES');
insert into public.canton (id, provincia_id, nombre) OVERRIDING SYSTEM VALUE values(240,3,'CAÑAR');
insert into public.canton (id, provincia_id, nombre) OVERRIDING SYSTEM VALUE values(241,3,'SUSCAL');
insert into public.canton (id, provincia_id, nombre) OVERRIDING SYSTEM VALUE values(245,3,'BIBLIAN');
insert into public.canton (id, provincia_id, nombre) OVERRIDING SYSTEM VALUE values(250,3,'LA TRONCAL');
insert into public.canton (id, provincia_id, nombre) OVERRIDING SYSTEM VALUE values(251,26,'ISRAEL');
insert into public.canton (id, provincia_id, nombre) OVERRIDING SYSTEM VALUE values(255,15,'EL CHACO');
insert into public.canton (id, provincia_id, nombre) OVERRIDING SYSTEM VALUE values(260,1,'CUENCA');
insert into public.canton (id, provincia_id, nombre) OVERRIDING SYSTEM VALUE values(261,26,'ITALIA');
insert into public.canton (id, provincia_id, nombre) OVERRIDING SYSTEM VALUE values(265,1,'GUALACEO');
insert into public.canton (id, provincia_id, nombre) OVERRIDING SYSTEM VALUE values(270,1,'GIRON');
insert into public.canton (id, provincia_id, nombre) OVERRIDING SYSTEM VALUE values(271,26,'JAPON');
insert into public.canton (id, provincia_id, nombre) OVERRIDING SYSTEM VALUE values(275,1,'PAUTE');
insert into public.canton (id, provincia_id, nombre) OVERRIDING SYSTEM VALUE values(280,1,'SIGSIG');
insert into public.canton (id, provincia_id, nombre) OVERRIDING SYSTEM VALUE values(281,28,'MEXICO');
insert into public.canton (id, provincia_id, nombre) OVERRIDING SYSTEM VALUE values(285,1,'SANTA ISABEL');
insert into public.canton (id, provincia_id, nombre) OVERRIDING SYSTEM VALUE values(290,11,'CATAMAYO');
insert into public.canton (id, provincia_id, nombre) OVERRIDING SYSTEM VALUE values(295,11,'ZAPOTILLO');
insert into public.canton (id, provincia_id, nombre) OVERRIDING SYSTEM VALUE values(300,11,'LOJA');
insert into public.canton (id, provincia_id, nombre) OVERRIDING SYSTEM VALUE values(301,26,'PAISES BAJOS (HOLANDA)');
insert into public.canton (id, provincia_id, nombre) OVERRIDING SYSTEM VALUE values(305,11,'SARAGURO');
insert into public.canton (id, provincia_id, nombre) OVERRIDING SYSTEM VALUE values(310,11,'PALTAS');
insert into public.canton (id, provincia_id, nombre) OVERRIDING SYSTEM VALUE values(311,11,'OLMEDO');
insert into public.canton (id, provincia_id, nombre) OVERRIDING SYSTEM VALUE values(312,28,'PANAMA');
insert into public.canton (id, provincia_id, nombre) OVERRIDING SYSTEM VALUE values(315,11,'CELICA');
insert into public.canton (id, provincia_id, nombre) OVERRIDING SYSTEM VALUE values(320,11,'CALVAS');
insert into public.canton (id, provincia_id, nombre) OVERRIDING SYSTEM VALUE values(321,28,'PARAGUAY');
insert into public.canton (id, provincia_id, nombre) OVERRIDING SYSTEM VALUE values(325,11,'MACARA');
insert into public.canton (id, provincia_id, nombre) OVERRIDING SYSTEM VALUE values(330,11,'PUYANGO');
insert into public.canton (id, provincia_id, nombre) OVERRIDING SYSTEM VALUE values(331,28,'PERU');
insert into public.canton (id, provincia_id, nombre) OVERRIDING SYSTEM VALUE values(335,11,'GONZANAMA');
insert into public.canton (id, provincia_id, nombre) OVERRIDING SYSTEM VALUE values(340,11,'ESPINDOLA');
insert into public.canton (id, provincia_id, nombre) OVERRIDING SYSTEM VALUE values(341,28,'EGIPTO');
insert into public.canton (id, provincia_id, nombre) OVERRIDING SYSTEM VALUE values(345,11,'SOZORANGA');
insert into public.canton (id, provincia_id, nombre) OVERRIDING SYSTEM VALUE values(350,7,'MACHALA');
insert into public.canton (id, provincia_id, nombre) OVERRIDING SYSTEM VALUE values(351,28,'REPUBLICA DOMINICANA');
insert into public.canton (id, provincia_id, nombre) OVERRIDING SYSTEM VALUE values(355,7,'SANTA ROSA');
insert into public.canton (id, provincia_id, nombre) OVERRIDING SYSTEM VALUE values(360,7,'ZARUMA');
insert into public.canton (id, provincia_id, nombre) OVERRIDING SYSTEM VALUE values(361,26,'SUECIA');
insert into public.canton (id, provincia_id, nombre) OVERRIDING SYSTEM VALUE values(365,7,'PASAJE');
insert into public.canton (id, provincia_id, nombre) OVERRIDING SYSTEM VALUE values(370,7,'PIÑAS');
insert into public.canton (id, provincia_id, nombre) OVERRIDING SYSTEM VALUE values(371,26,'SUIZA');
insert into public.canton (id, provincia_id, nombre) OVERRIDING SYSTEM VALUE values(375,7,'ARENILLAS');
insert into public.canton (id, provincia_id, nombre) OVERRIDING SYSTEM VALUE values(380,7,'EL GUABO');
insert into public.canton (id, provincia_id, nombre) OVERRIDING SYSTEM VALUE values(381,26,'FEDERACION DE RUSIA');
insert into public.canton (id, provincia_id, nombre) OVERRIDING SYSTEM VALUE values(385,9,'EL EMPALME');
insert into public.canton (id, provincia_id, nombre) OVERRIDING SYSTEM VALUE values(390,9,'GUAYAQUIL');
insert into public.canton (id, provincia_id, nombre) OVERRIDING SYSTEM VALUE values(391,28,'URUGUAY');
insert into public.canton (id, provincia_id, nombre) OVERRIDING SYSTEM VALUE values(395,9,'YAGUACHI');
insert into public.canton (id, provincia_id, nombre) OVERRIDING SYSTEM VALUE values(400,9,'DAULE');
insert into public.canton (id, provincia_id, nombre) OVERRIDING SYSTEM VALUE values(401,28,'VENEZUELA');
insert into public.canton (id, provincia_id, nombre) OVERRIDING SYSTEM VALUE values(405,24,'SALINAS');
insert into public.canton (id, provincia_id, nombre) OVERRIDING SYSTEM VALUE values(410,24,'SANTA ELENA');
insert into public.canton (id, provincia_id, nombre) OVERRIDING SYSTEM VALUE values(411,26,'INDONESIA');
insert into public.canton (id, provincia_id, nombre) OVERRIDING SYSTEM VALUE values(415,9,'BALZAR');
insert into public.canton (id, provincia_id, nombre) OVERRIDING SYSTEM VALUE values(420,9,'MILAGRO');
insert into public.canton (id, provincia_id, nombre) OVERRIDING SYSTEM VALUE values(425,9,'SAMBORONDON');
insert into public.canton (id, provincia_id, nombre) OVERRIDING SYSTEM VALUE values(430,9,'SALITRE');
insert into public.canton (id, provincia_id, nombre) OVERRIDING SYSTEM VALUE values(435,9,'NARANJAL');
insert into public.canton (id, provincia_id, nombre) OVERRIDING SYSTEM VALUE values(440,13,'PORTOVIEJO');
insert into public.canton (id, provincia_id, nombre) OVERRIDING SYSTEM VALUE values(441,28,'SUDAFRICA');
insert into public.canton (id, provincia_id, nombre) OVERRIDING SYSTEM VALUE values(445,13,'MONTECRISTI');
insert into public.canton (id, provincia_id, nombre) OVERRIDING SYSTEM VALUE values(446,13,'JARAMIJO');
insert into public.canton (id, provincia_id, nombre) OVERRIDING SYSTEM VALUE values(450,13,'MANTA');
insert into public.canton (id, provincia_id, nombre) OVERRIDING SYSTEM VALUE values(451,26,'TURQUIA');
insert into public.canton (id, provincia_id, nombre) OVERRIDING SYSTEM VALUE values(455,13,'JIPIJAPA');
insert into public.canton (id, provincia_id, nombre) OVERRIDING SYSTEM VALUE values(460,13,'24 DE MAYO');
insert into public.canton (id, provincia_id, nombre) OVERRIDING SYSTEM VALUE values(465,13,'ROCAFUERTE');
insert into public.canton (id, provincia_id, nombre) OVERRIDING SYSTEM VALUE values(470,13,'SANTA ANA');
insert into public.canton (id, provincia_id, nombre) OVERRIDING SYSTEM VALUE values(475,13,'SUCRE');
insert into public.canton (id, provincia_id, nombre) OVERRIDING SYSTEM VALUE values(476,13,'JAMA');
insert into public.canton (id, provincia_id, nombre) OVERRIDING SYSTEM VALUE values(477,13,'SAN VICENTE');
insert into public.canton (id, provincia_id, nombre) OVERRIDING SYSTEM VALUE values(480,13,'CHONE');
insert into public.canton (id, provincia_id, nombre) OVERRIDING SYSTEM VALUE values(485,13,'BOLIVAR');
insert into public.canton (id, provincia_id, nombre) OVERRIDING SYSTEM VALUE values(490,13,'JUNIN');
insert into public.canton (id, provincia_id, nombre) OVERRIDING SYSTEM VALUE values(495,13,'PAJAN');
insert into public.canton (id, provincia_id, nombre) OVERRIDING SYSTEM VALUE values(500,13,'EL CARMEN');
insert into public.canton (id, provincia_id, nombre) OVERRIDING SYSTEM VALUE values(505,9,'EL TRIUNFO');
insert into public.canton (id, provincia_id, nombre) OVERRIDING SYSTEM VALUE values(510,9,'NARANJITO');
insert into public.canton (id, provincia_id, nombre) OVERRIDING SYSTEM VALUE values(515,12,'BABAHOYO');
insert into public.canton (id, provincia_id, nombre) OVERRIDING SYSTEM VALUE values(516,12,'VALENCIA');
insert into public.canton (id, provincia_id, nombre) OVERRIDING SYSTEM VALUE values(520,12,'BABA');
insert into public.canton (id, provincia_id, nombre) OVERRIDING SYSTEM VALUE values(525,12,'VINCES');
insert into public.canton (id, provincia_id, nombre) OVERRIDING SYSTEM VALUE values(530,12,'PUEBLO VIEJO');
insert into public.canton (id, provincia_id, nombre) OVERRIDING SYSTEM VALUE values(535,12,'URDANETA');
insert into public.canton (id, provincia_id, nombre) OVERRIDING SYSTEM VALUE values(540,12,'QUEVEDO');
insert into public.canton (id, provincia_id, nombre) OVERRIDING SYSTEM VALUE values(545,12,'VENTANAS');
insert into public.canton (id, provincia_id, nombre) OVERRIDING SYSTEM VALUE values(546,12,'QUINSALOMA');
insert into public.canton (id, provincia_id, nombre) OVERRIDING SYSTEM VALUE values(550,13,'TOSAGUA');
insert into public.canton (id, provincia_id, nombre) OVERRIDING SYSTEM VALUE values(555,1,'PUCARA');
insert into public.canton (id, provincia_id, nombre) OVERRIDING SYSTEM VALUE values(556,1,'CAMILO PONCE ENRIQUEZ');
insert into public.canton (id, provincia_id, nombre) OVERRIDING SYSTEM VALUE values(560,8,'ESMERALDAS');
insert into public.canton (id, provincia_id, nombre) OVERRIDING SYSTEM VALUE values(561,8,'RIO VERDE');
insert into public.canton (id, provincia_id, nombre) OVERRIDING SYSTEM VALUE values(565,8,'ELOY ALFARO');
insert into public.canton (id, provincia_id, nombre) OVERRIDING SYSTEM VALUE values(570,8,'MUISNE');
insert into public.canton (id, provincia_id, nombre) OVERRIDING SYSTEM VALUE values(575,8,'QUININDE');
insert into public.canton (id, provincia_id, nombre) OVERRIDING SYSTEM VALUE values(580,8,'SAN LORENZO');
insert into public.canton (id, provincia_id, nombre) OVERRIDING SYSTEM VALUE values(585,7,'CHILLA');
insert into public.canton (id, provincia_id, nombre) OVERRIDING SYSTEM VALUE values(590,14,'MORONA');
insert into public.canton (id, provincia_id, nombre) OVERRIDING SYSTEM VALUE values(595,14,'GUALAQUIZA');
insert into public.canton (id, provincia_id, nombre) OVERRIDING SYSTEM VALUE values(600,14,'LIMON INDANZA');
insert into public.canton (id, provincia_id, nombre) OVERRIDING SYSTEM VALUE values(605,14,'SANTIAGO');
insert into public.canton (id, provincia_id, nombre) OVERRIDING SYSTEM VALUE values(610,14,'SUCUA');
insert into public.canton (id, provincia_id, nombre) OVERRIDING SYSTEM VALUE values(611,14,'LOGROÑO');
insert into public.canton (id, provincia_id, nombre) OVERRIDING SYSTEM VALUE values(615,14,'PALORA');
insert into public.canton (id, provincia_id, nombre) OVERRIDING SYSTEM VALUE values(620,15,'TENA');
insert into public.canton (id, provincia_id, nombre) OVERRIDING SYSTEM VALUE values(621,15,'C. J. AROSEMENA TOLA');
insert into public.canton (id, provincia_id, nombre) OVERRIDING SYSTEM VALUE values(625,21,'LAGO AGRIO');
insert into public.canton (id, provincia_id, nombre) OVERRIDING SYSTEM VALUE values(626,21,'CUYABENO');
insert into public.canton (id, provincia_id, nombre) OVERRIDING SYSTEM VALUE values(630,22,'AGUARICO');
insert into public.canton (id, provincia_id, nombre) OVERRIDING SYSTEM VALUE values(635,15,'QUIJOS');
insert into public.canton (id, provincia_id, nombre) OVERRIDING SYSTEM VALUE values(640,21,'SUCUMBIOS');
insert into public.canton (id, provincia_id, nombre) OVERRIDING SYSTEM VALUE values(645,22,'FCO.DE ORELLANA');
insert into public.canton (id, provincia_id, nombre) OVERRIDING SYSTEM VALUE values(650,21,'PUTUMAYO');
insert into public.canton (id, provincia_id, nombre) OVERRIDING SYSTEM VALUE values(655,19,'ZAMORA');
insert into public.canton (id, provincia_id, nombre) OVERRIDING SYSTEM VALUE values(660,19,'CHINCHIPE');
insert into public.canton (id, provincia_id, nombre) OVERRIDING SYSTEM VALUE values(661,19,'PALANDA');
insert into public.canton (id, provincia_id, nombre) OVERRIDING SYSTEM VALUE values(665,19,'YACUAMBI');
insert into public.canton (id, provincia_id, nombre) OVERRIDING SYSTEM VALUE values(670,19,'YANZATZA');
insert into public.canton (id, provincia_id, nombre) OVERRIDING SYSTEM VALUE values(675,9,'PALESTINA');
insert into public.canton (id, provincia_id, nombre) OVERRIDING SYSTEM VALUE values(680,16,'PASTAZA');
insert into public.canton (id, provincia_id, nombre) OVERRIDING SYSTEM VALUE values(685,16,'MERA');
insert into public.canton (id, provincia_id, nombre) OVERRIDING SYSTEM VALUE values(690,7,'PORTOVELO');
insert into public.canton (id, provincia_id, nombre) OVERRIDING SYSTEM VALUE values(695,7,'HUAQUILLAS');
insert into public.canton (id, provincia_id, nombre) OVERRIDING SYSTEM VALUE values(700,15,'ARCHIDONA');
insert into public.canton (id, provincia_id, nombre) OVERRIDING SYSTEM VALUE values(705,7,'ATAHUALPA');
insert into public.canton (id, provincia_id, nombre) OVERRIDING SYSTEM VALUE values(710,12,'MONTALVO');
insert into public.canton (id, provincia_id, nombre) OVERRIDING SYSTEM VALUE values(715,9,'PEDRO CARBO');
insert into public.canton (id, provincia_id, nombre) OVERRIDING SYSTEM VALUE values(720,21,'SHUSHUFINDI');
insert into public.canton (id, provincia_id, nombre) OVERRIDING SYSTEM VALUE values(725,22,'JOYA DE LOS SACHAS');
insert into public.canton (id, provincia_id, nombre) OVERRIDING SYSTEM VALUE values(730,11,'PINDAL');
insert into public.canton (id, provincia_id, nombre) OVERRIDING SYSTEM VALUE values(735,9,'PLAYAS');
insert into public.canton (id, provincia_id, nombre) OVERRIDING SYSTEM VALUE values(740,11,'QUILANGA');
insert into public.canton (id, provincia_id, nombre) OVERRIDING SYSTEM VALUE values(745,21,'CASCALES');
insert into public.canton (id, provincia_id, nombre) OVERRIDING SYSTEM VALUE values(750,12,'PALENQUE');
insert into public.canton (id, provincia_id, nombre) OVERRIDING SYSTEM VALUE values(755,7,'LAS LAJAS');
insert into public.canton (id, provincia_id, nombre) OVERRIDING SYSTEM VALUE values(760,2,'CALUMA');
insert into public.canton (id, provincia_id, nombre) OVERRIDING SYSTEM VALUE values(765,3,'EL TAMBO');
insert into public.canton (id, provincia_id, nombre) OVERRIDING SYSTEM VALUE values(770,17,'SAN MIGUEL DE LOS BANCOS');
insert into public.canton (id, provincia_id, nombre) OVERRIDING SYSTEM VALUE values(775,19,'EL PANGUI');
insert into public.canton (id, provincia_id, nombre) OVERRIDING SYSTEM VALUE values(780,1,'OÑA');
insert into public.canton (id, provincia_id, nombre) OVERRIDING SYSTEM VALUE values(785,8,'ATACAMES');
insert into public.canton (id, provincia_id, nombre) OVERRIDING SYSTEM VALUE values(790,9,'SIMON BOLIVAR');
insert into public.canton (id, provincia_id, nombre) OVERRIDING SYSTEM VALUE values(795,14,'HUAMBOYA');
insert into public.canton (id, provincia_id, nombre) OVERRIDING SYSTEM VALUE values(796,14,'PABLO SEXTO');
insert into public.canton (id, provincia_id, nombre) OVERRIDING SYSTEM VALUE values(797,14,'TIWINTZA');
insert into public.canton (id, provincia_id, nombre) OVERRIDING SYSTEM VALUE values(800,20,'SAN CRISTOBAL');
insert into public.canton (id, provincia_id, nombre) OVERRIDING SYSTEM VALUE values(805,20,'SANTA CRUZ');
insert into public.canton (id, provincia_id, nombre) OVERRIDING SYSTEM VALUE values(810,20,'ISABELA');
insert into public.canton (id, provincia_id, nombre) OVERRIDING SYSTEM VALUE values(815,11,'CHAGUARPAMBA');
insert into public.canton (id, provincia_id, nombre) OVERRIDING SYSTEM VALUE values(820,9,'DURAN');
insert into public.canton (id, provincia_id, nombre) OVERRIDING SYSTEM VALUE values(825,5,'LA MANA');
insert into public.canton (id, provincia_id, nombre) OVERRIDING SYSTEM VALUE values(830,6,'PALLATANGA');
insert into public.canton (id, provincia_id, nombre) OVERRIDING SYSTEM VALUE values(835,9,'A.BAQUERIZO MORENO');
insert into public.canton (id, provincia_id, nombre) OVERRIDING SYSTEM VALUE values(840,13,'PICHINCHA');
insert into public.canton (id, provincia_id, nombre) OVERRIDING SYSTEM VALUE values(845,18,'CEVALLOS');
insert into public.canton (id, provincia_id, nombre) OVERRIDING SYSTEM VALUE values(850,18,'MOCHA');
insert into public.canton (id, provincia_id, nombre) OVERRIDING SYSTEM VALUE values(855,1,'SAN FERNANDO');
insert into public.canton (id, provincia_id, nombre) OVERRIDING SYSTEM VALUE values(860,7,'MARCABELI');
insert into public.canton (id, provincia_id, nombre) OVERRIDING SYSTEM VALUE values(865,21,'GONZALO PIZARRO');
insert into public.canton (id, provincia_id, nombre) OVERRIDING SYSTEM VALUE values(870,9,'SANTA LUCIA');
insert into public.canton (id, provincia_id, nombre) OVERRIDING SYSTEM VALUE values(875,7,'BALSAS');
insert into public.canton (id, provincia_id, nombre) OVERRIDING SYSTEM VALUE values(880,16,'SANTA CLARA');
insert into public.canton (id, provincia_id, nombre) OVERRIDING SYSTEM VALUE values(881,16,'ARAJUNO');
insert into public.canton (id, provincia_id, nombre) OVERRIDING SYSTEM VALUE values(885,1,'NABON');
insert into public.canton (id, provincia_id, nombre) OVERRIDING SYSTEM VALUE values(890,9,'CRNL MARCELINO MARIDUENAS');
insert into public.canton (id, provincia_id, nombre) OVERRIDING SYSTEM VALUE values(895,17,'PEDRO VICENTE MALDONADO');
insert into public.canton (id, provincia_id, nombre) OVERRIDING SYSTEM VALUE values(896,17,'PUERTO QUITO');
insert into public.canton (id, provincia_id, nombre) OVERRIDING SYSTEM VALUE values(900,6,'CUMANDA');
insert into public.canton (id, provincia_id, nombre) OVERRIDING SYSTEM VALUE values(905,3,'DELEG');
insert into public.canton (id, provincia_id, nombre) OVERRIDING SYSTEM VALUE values(910,13,'PEDERNALES');
insert into public.canton (id, provincia_id, nombre) OVERRIDING SYSTEM VALUE values(915,1,'CHORDELEG');
insert into public.canton (id, provincia_id, nombre) OVERRIDING SYSTEM VALUE values(920,9,'LOMAS DE SARGENTILLO');
insert into public.canton (id, provincia_id, nombre) OVERRIDING SYSTEM VALUE values(925,14,'SAN JUAN BOSCO');
insert into public.canton (id, provincia_id, nombre) OVERRIDING SYSTEM VALUE values(926,14,'TAISHA');
insert into public.canton (id, provincia_id, nombre) OVERRIDING SYSTEM VALUE values(930,5,'SIGCHOS');
insert into public.canton (id, provincia_id, nombre) OVERRIDING SYSTEM VALUE values(935,22,'LORETO');
insert into public.canton (id, provincia_id, nombre) OVERRIDING SYSTEM VALUE values(940,9,'NOBOL / PIEDRAHITA');
insert into public.canton (id, provincia_id, nombre) OVERRIDING SYSTEM VALUE values(945,12,'BUENA FE');
insert into public.canton (id, provincia_id, nombre) OVERRIDING SYSTEM VALUE values(946,12,'MOCACHE');
insert into public.canton (id, provincia_id, nombre) OVERRIDING SYSTEM VALUE values(950,2,'LAS NAVES');
insert into public.canton (id, provincia_id, nombre) OVERRIDING SYSTEM VALUE values(955,1,'SEVILLA DE ORO');
insert into public.canton (id, provincia_id, nombre) OVERRIDING SYSTEM VALUE values(960,1,'EL PAN');
insert into public.canton (id, provincia_id, nombre) OVERRIDING SYSTEM VALUE values(965,24,'LA LIBERTAD');
insert into public.canton (id, provincia_id, nombre) OVERRIDING SYSTEM VALUE values(970,13,'OLMEDO');
insert into public.canton (id, provincia_id, nombre) OVERRIDING SYSTEM VALUE values(975,13,'PUERTO LOPEZ');
insert into public.canton (id, provincia_id, nombre) OVERRIDING SYSTEM VALUE values(980,19,'CENTINELA DEL CONDOR');
insert into public.canton (id, provincia_id, nombre) OVERRIDING SYSTEM VALUE values(981,19,'PAQUISHA');
insert into public.canton (id, provincia_id, nombre) OVERRIDING SYSTEM VALUE values(982,23,'LA CONCORDIA');
insert into public.canton (id, provincia_id, nombre) OVERRIDING SYSTEM VALUE values(985,9,'GRAL. A. ELIZALDE');
insert into public.canton (id, provincia_id, nombre) OVERRIDING SYSTEM VALUE values(986,9,'ISIDRO AYORA');
insert into public.canton (id, provincia_id, nombre) OVERRIDING SYSTEM VALUE values(990,1,'GUACHAPALA');
insert into public.canton (id, provincia_id, nombre) OVERRIDING SYSTEM VALUE values(995,4,'SAN PEDRO DE HUACA');

